sonar.projectKey=Nicolas2003_Property_Valuation
sonar.organization=nicolas2003

sonar.projectName=Property Valuation
sonar.sourceEncoding=UTF-8

sonar.sources=app.py,estimator,config,scripts
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
