service: property_valuation

image: nicolas2003/property_valuation

servers:
  web:
    - 209.38.93.10

proxy:
  ssl: true
  host: houses.kmaster.app
  app_port: 8501
  healthcheck:
    path: /_stcore/health

registry:
  server: ghcr.io
  username: nicolas2003
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    PGHOST: db-postgresql-syd1-66096-do-user-7536526-0.h.db.ondigitalocean.com
    PGPORT: 25060
    PGDATABASE: property_valuation
    PGUSER: property_valuation
    PGSSLMODE: require
  secret:
    - PGPASSWORD

aliases:
  logs: app logs -f
  shell: app exec --interactive --reuse "bash"
